Решение задач - Основы: Часть 2
js-tasks-ru/vue-20240924_aysen-elyaz pull request #3
Opened 2024-10-10 15:12 UTC by Iliya396

2024-10-10 15:13 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-13 22:26 UTC, ShGKme requested changes
Требуется исправление `computed-а` в `02-basics-2/30-calculator`.

Остальные задачи приняты

2024-10-13 22:26 UTC, ShGKme commented on 02-basics-2/10-counter/CounterApp.js
> +      <span class="count" data-testid="count">{{count}}</span>
Напомню, что у текстовой интерполяции принято добавлять пробелы: `{{ count }}`

2024-10-13 22:26 UTC, ShGKme commented on 02-basics-2/10-counter/CounterApp.js
> +        :disabled = "count === maxVal"
А у атрибутов, как в HTML - наоборот, не обособляют = пробелами: `:disabled="count === maxVal"`

2024-10-13 22:26 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        second = ref(0)
Объявление `ref` переменной как `let` обычно является ошибкой:

- Либо эта переменная никогда не меняется, а значит должна быть `const`
- Либо меняется переменная, вместо изменения значения переменной через `.value`, что приведёт к потере значения изначального `ref`

2024-10-13 22:26 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +    })
Это вычисляемое свойство вычисляет результат вычисления. В итоге в вычисляемом свойстве `calculatedResult` находится результат вычисления.

Но в процессе этого вычисления, функция вычисления ещё и меняет другую переменную - `result`.

Вычисляемые свойства ни в коем случае не должны иметь побочных эффектов в своём вычислении и должны только возвращать результат вычисления.

Мы не контролируем как и когда это вычисляемое свойство будет вычислено. И если сам факт его вычисления (даже просто для отображения в девтулсах) будет менять состояние приложения, могет быть неожиданные эффекты.

2024-10-13 22:26 UTC, ShGKme commented on 02-basics-2/40-marked-emails/MarkedEmailsApp.js
> +    })
Здесь хорошо подойдёт метод `map`, а для поиска подстроки - `includeы`.

2024-10-13 22:26 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +       if (picked.value < meetupCount) { picked.value++ }
Можно не добавлять таких проверок, если мы считаем, что функции используются корректно. (От некорректного вызова защищает отключение кнопок).

2024-10-14 11:26 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-14 11:36 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-14 18:33 UTC, ShGKme approved these changes

2024-10-14 18:33 UTC, ShGKme commented on 02-basics-2/10-counter/CounterApp.js
> +        :disabled = "count===maxVal"
Пробел не ставят вокруг = у атрибута в HTML, не оператора в JS: 
`:disabled="count===maxVal"`

2024-10-14 18:34 UTC, merged