Исправления в Решение задач - Компоненты
js-tasks-ru/vue-20240924_aysen-elyaz pull request #5
Opened 2024-10-27 16:53 UTC by Iliya396

2024-10-27 16:54 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-11-01 15:57 UTC, ShGKme requested changes
В `03-components/50-weather-components` потерялась реактивность почти во всех компонентах.

2024-11-01 15:57 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +          break;
break после return не нужен, return уже завершает работу функции

2024-11-01 15:57 UTC, ShGKme commented on 02-basics-2/40-marked-emails/MarkedEmailsApp.js
> +    let styleFlags = new Array(emails.length).fill(false),
Этот массив нигде не используется, как настоящий массив с данными. Единственное его применение - иметь что-то для `map`, чтобы сделать из `map` обычный цикл. Вместо этого `map` должен перебирать массив `emails`, так как отображение идёт именно из него.

2024-11-01 15:57 UTC, ShGKme commented on 03-components/30-removable-emails/EmailList.js
> +  emits: ['removeEmailEvent'],
В название событий никогда не добавляют `Event`, как  `Prop` в имена параметров.

2024-11-01 15:57 UTC, ShGKme commented on 03-components/40-UiCounter/App.js
> +    const initCount2 = ref(2)
Переменные `initCount` не имеют смысла, как реактивные - на них нигде нет реакции, они не изменяются, а используются как константы.

2024-11-01 15:57 UTC, ShGKme commented on 03-components/50-weather-components/components/UiWeatherAlert.js
> +    const alert = ref(props.weatherAlert)
Здесь "потерялась реактивность". При изменении параметра `weatherAlert` компонент продолжит рендерить старое значение

2024-11-01 15:57 UTC, ShGKme commented on 03-components/50-weather-components/components/UiWeatherAlert.js
> +  props: ['weatherAlert'],
Лучше всегда подробнее описывать параметры: тип, обязательность. Хотя бы `type: Object` для объектов.

2024-11-10 12:57 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-06 12:17 UTC, ShGKme requested changes
Старая проблема с реактивностью пропсов всё ещё осталась

2024-12-06 12:17 UTC, ShGKme commented on 03-components/50-weather-components/components/UiWeatherCard.js
> +    const item = ref(props.cardItem)
Осталась проблема с прошлого ревью.

Здесь создаётся новая переменная `item`. Это реактивная переменная и её начальное значение берётся из `props.cardItem`. Но это только начальное значение переменной. `ref` не создаёт постоянной связи.

Это тоже самое, что просто создать новую переменную: 

```js
const item = { value: props.cardItem }
```

При изменении `props.cardItem`, новая переменная `item` не изменится.

Нужно либо использовать пропс напрямую (в шаблоне можно просто `cardItem`), либо создавать переменную через `toRef/toRefs` утилиты. Именно эти утилиты создают реактивную переменную, связанную с другим объектом.

2024-12-06 12:17 UTC, ShGKme commented on 03-components/50-weather-components/components/UiWeatherCard.js
> +    const item = ref(props.cardItem)
https://ru.vuejs.org/api/reactivity-utilities.html#toref

2024-12-06 12:17 UTC, ShGKme commented on 03-components/50-weather-components/components/UiWeatherCard.js
> +    const item = ref(props.cardItem)
Такая же проблема в остальных компонентах в этой задаче.

2024-12-06 12:17 UTC, ShGKme commented on 03-components/50-weather-components/components/UiWeatherCard.js
> +    const item = ref(props.cardItem)
Это серьёзная проблема, которая часто приводит к багам в проектах

2024-12-06 12:17 UTC, ShGKme commented on 04-sfc/10-MeetupView-script-setup/MeetupAgenda.vue
> +})
Можно не генерировать имя через `defineOptions`, если оно совпадает с именем файла. Для `<script setup>` Vue сам сгенерирует `__name` по имени файла.

2024-12-06 12:17 UTC, ShGKme commented on 04-sfc/30-UiStretch/UiStretch.vue
>  .stretch-container > img,
В этой задаче проблема осталась.

Селектор `.stretch-container > *` работал и в изначальной версии, так как для `*` не применяется инкапсуляция `scoped` стилей. `important` тоже не нужен, так как нет стилей, которые требуется перебить приоритетом.

А вот следующее правило с `> img`, `> video` - не работает, так как на `img` селектор и другие уже накладывается инкапсуляция, и пришедшие в слот элементы стилей не получают. Именно здесь нужен `slotted`

2024-12-07 16:17 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-07 16:30 UTC, ShGKme approved these changes
Принято

2024-12-07 16:32 UTC, merged